<Project>
  <PropertyGroup>
    <Version>3.2.0</Version>
    <AssemblyVersion>3.2.0.0</AssemblyVersion>
    <FileVersion>3.2.0.0</FileVersion>
    <Company>onlytrisdev</Company>
    <Authors>onlytrisdev</Authors>
    <Product>Chrome MV2 Launcher</Product>
    <RepositoryUrl>https://github.com/onlytrisdev/chrome-enable-mv2</RepositoryUrl>
  </PropertyGroup>
</Project>
